SELECT P.BIRTH_DATE 생년월일, P.PLAYER_NAME 선수
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL
ORDER BY P.BIRTH_DATE DESC;

SELECT count(*) 선수인원 -- 486명
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL
ORDER BY P.BIRTH_DATE DESC;

--1단계
SELECT P.BIRTH_DATE 생년월일,
       P.PLAYER_NAME 선수
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL    
ORDER BY P.BIRTH_DATE DESC;
--답
--1997/10/24	안소정
--1996/12/09	정준
--1996/04/26	선원길
--1996/04/25	김강진
--1996/04/07	박성호

--2단계
SELECT ROWNUM 번호, P.BIRTH_DATE 생년월일,
       P.PLAYER_NAME 선수
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL AND
      ROWNUM BETWEEN 1 AND 5
ORDER BY P.BIRTH_DATE DESC;

SELECT P.BIRTH_DATE 생년월일,
       P.PLAYER_NAME 선수
FROM PLAYER P
WHERE P.BIRTH_DATE IS NOT NULL AND
      ROWNUM BETWEEN 1 AND 5
ORDER BY P.BIRTH_DATE DESC;
--답
--1989/07/13	김규호
--1987/08/30	우르모브
--1984/06/05	김장관
--1983/06/23	김민성
--1982/11/01	윤희준
--1989 김규호 외 랜덤값으로 출력됨 --> 틀린값

--3단계
SELECT P.BIRTH_DATE 생년월일, P.PLAYER_NAME 선수
FROM (
    SELECT P.BIRTH_DATE, P.PLAYER_NAME
    FROM PLAYER P
    WHERE P.BIRTH_DATE IS NOT NULL
    ORDER BY P.BIRTH_DATE DESC) P
WHERE ROWNUM BETWEEN 1 AND 5; 

--4단계 
SELECT BIRTH_DATE 생년월일, PLAYER_NAME 선수
    FROM (SELECT ROWNUM SEQ, T1.* 
            FROM(
                SELECT P.BIRTH_DATE, P.PLAYER_NAME
                    FROM PLAYER P
                WHERE P.BIRTH_DATE IS NOT NULL 
                ORDER BY P.BIRTH_DATE DESC)T1)T2
WHERE T2.SEQ BETWEEN 6 AND 10
ORDER BY T2.SEQ DESC;
 






