--컬럼 이름바꾸기
ALTER TABLE CUSTOMERS RENAME COLUMN SSN TO POSTALCODE;
ALTER TABLE EMPLOYEES RENAME COLUMN LAST_NAME TO MANAGER;

--컬럼 추가하기
ALTER TABLE EMPLOYEES ADD NOTES VARCHAR2(20);

--참조되고있는것까지 테이블지우기
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;

SELECT * FROM USER_SEQUENCES;
CREATE SEQUENCE EMP_SEQ
    START WITH 1000
    ;
INSERT INTO EMPLOYEES(EMPLOYEE_ID, MANAGER, NAME,BIRTH_DATE, PHOTO, NOTES)
VALUES(EMP_SEQ.NEXTVAL, 'MANAGER','김경민','9601010','KIM.JPG','매니저');

SELECT * FROM EMPLOYEES;
SELECT COUNT(*) FROM EMPLOYEES;

