SELECT * FROM TAB;
SELECT * FROM CUSTOMERS;

SELECT *
FROM CUSTOMERS
WHERE CUSTOMER_ID LIKE 'ronaldo'
;

UPDATE (SELECT *
FROM CUSTOMERS
WHERE CUSTOMER_ID LIKE 'ronaldo'
)
SET PASSWORD = 95 , PHONE = '010-000-0000', CITY = '서울시 강남구 선릉동', ADDRESS = '초등학교' , POSTALCODE = '061875'
;
